### ISSUE TITLE
Infinite Loop Created by Camera Zoom Function

### ISSUE THREAD

**Issue by razage** [IndieQuest/GodotRtsCameraController3D#1]
In the camera zoom code, you check `if zoom_speed_damp < 0.0001:` to see if you should reset the zoom direction. Since the zoom dampening is applied to the zoom direction, this never triggers and ends up calling the zoom function ~2 times per frame on my system. While the profiler didn't show any serious impact, I imagine that this could become a memory leak or something like that in a full game and/or over time.

I changed my code to the following snippet to fix the issue. I use the absolute value because one of the zoom directions is negative, so it would always be under 0.0001. I'm not sure if you'd do this a different way, but here's what I did.

```
if abs(zoom_direction) < 0.0001:
		zoom_direction = 0
```

**Comment by IndieQuest** [comment]
Thank you so much for catching this error!
I pushed a fix to the master.

**Comment by IndieQuest** [comment]
now checking aginst the correct variable
